blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Kotlinlang Slack
    url: https://surveys.jetbrains.com/s3/kotlin-slack-sign-up
    about: Ask questions, share knowledge, and discuss kotlinx.serialization usage with the community
